ListenIP: "0.0.0.0"
ListenPort: "8080"
Author:
  Name: "Md. Sayeed Rahman"
  Github: "github.com/sayeed1999"
API:
  Name: "Social Connect"
  Version: "1.0.0"
Database:
  Host: "127.0.0.1"
  Port: "5433"
  User: "user"
  Password: "password"
  Name: "social-connect"
